version: '3.8'

services:
  # Funds unlocker bot - runs every 10 minutes to release deposits
  funds-unlocker:
    image: mirind4/funds-unlocker:latest

    environment:
      RPC_ENDPOINT: wss://hydration.ibp.network

    # Mount account.json and password
    secrets:
      - account_json
      - account_password

    # Override the default command to read secrets and pass them to bot-loop.sh
    command: sh -c 'exec ./bot-loop.sh "$${RPC_ENDPOINT}" /run/secrets/account_json "$$(cat /run/secrets/account_password)"'

    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s

      rollback_config:
        parallelism: 1
        order: start-first

      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - funds-unlocker-network

networks:
  funds-unlocker-network:
    driver: overlay
    attachable: true

secrets:
  # account.json file - contains the account keystore exported from polkadot.js
  account_json:
    external: true

  # account password - plain text password
  account_password:
    external: true
